language: php
sudo: required
php:
 - '5.5'
 - '5.6'
 - '7.1'

services:
 - mysql

before_script:
 - composer self-update
 - chmod ugo+x bin/travis.sh
 - ./bin/travis.sh $(phpenv version-name) $(pwd)

install:
 - travis_retry composer install --no-interaction --prefer-source --dev
